# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['analisi_trafficonewfct_profsari.py'],
    pathex=[],
    binaries=[],
    datas=[
    ],
    hiddenimports=[
        'pandas',
        'numpy',
        'matplotlib',
        'matplotlib.backends.backend_tkagg',
        'seaborn',
        'scipy',
        'scipy.stats',
        'scipy.stats._stats_py',
        'scipy.stats._continuous_distns',
        'scipy.stats._discrete_distns',
        'scipy.stats.distributions',
        'scipy.stats._distn_infrastructure',
        'scipy.special',
        'scipy.special._ufuncs',
        'scipy.integrate',
        'scipy.linalg',
        'scipy._lib',
        'scipy._lib._ccallback',
        'sklearn',
        'sklearn.ensemble',
        'sklearn.tree',
        'sklearn.utils',
        'statsmodels',
        'statsmodels.tsa.holtwinters',
        'statsmodels.tsa.statespace.sarimax',
        'tbats',
        'tbats.bats',
        'tbats.tbats',
        'prophet',
        'prophet.forecaster',
        'holidays',
        'holidays.countries.italy',
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'PIL',
        'PIL._tkinter_finder',
        'openpyxl',
        'xlsxwriter',
        'concurrent.futures',
    ],
    hookspath=['.'],  # Usa hook personalizzato nella directory corrente
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'IPython',
        'jupyter',
        'notebook',
        'sphinx',
        'pytest',
        'matplotlib.tests',
        'numpy.tests',
        'pandas.tests',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='AnalisiForecast',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # Mostra console per vedere output
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,  # Aggiungi un .ico se vuoi un'icona personalizzata
)
